const bancoQuestoes = {
"Língua Portuguesa": [
{ pergunta: "Na frase 'Os estudantes participaram do quiz', qual é o sujeito?", alternativas: ["Os estudantes", "Participaram", "Do quiz", "Estudantes participaram"], correta: 0 },
{ pergunta: "Qual alternativa apresenta um verbo?", alternativas: ["Escola", "Azul", "Aprender", "Caderno"], correta: 2 },
{ pergunta: "Qual palavra é um substantivo?", alternativas: ["Bonito", "Correr", "Casa", "Rapidamente"], correta: 2 },
{ pergunta: "Qual é o plural de cidadão?", alternativas: ["Cidadões", "Cidadãos", "Cidadães", "Cidadans"], correta: 1 },
{ pergunta: "Qual palavra é um adjetivo?", alternativas: ["Livro", "Bonito", "Mesa", "Estudar"], correta: 1 },
{ pergunta: "Qual sinal indica uma pergunta?", alternativas: [".", "!", "?", ":"], correta: 2 },
{ pergunta: "Qual é o antônimo de 'alto'?", alternativas: ["Grande", "Baixo", "Largo", "Fino"], correta: 1 },
{ pergunta: "Qual é o sinônimo de 'feliz'?", alternativas: ["Triste", "Alegre", "Bravo", "Calmo"], correta: 1 },
{ pergunta: "Em 'Maria comprou um livro', o verbo é:", alternativas: ["Maria", "Comprou", "Livro", "Um"], correta: 1 },
{ pergunta: "Qual palavra é um pronome?", alternativas: ["Eu", "Mesa", "Bonito", "Correr"], correta: 0 },
{ pergunta: "Qual é o feminino de ator?", alternativas: ["Atriz", "Atoresa", "Atrina", "Atriza"], correta: 0 },
{ pergunta: "Qual figura de linguagem compara elementos usando 'como'?", alternativas: ["Metáfora", "Comparação", "Ironia", "Hipérbole"], correta: 1 },
{ pergunta: "Qual é a função principal de uma notícia?", alternativas: ["Informar", "Vender", "Divertir", "Ensinar regras"], correta: 0 },
{ pergunta: "Qual palavra está escrita corretamente?", alternativas: ["Excessão", "Exceção", "Exeção", "Exsesão"], correta: 1 },
{ pergunta: "Qual é o aumentativo de casa?", alternativas: ["Casinha", "Casebre", "Casarão", "Casota"], correta: 2 },
{ pergunta: "Qual é o diminutivo de flor?", alternativas: ["Florona", "Florzinha", "Floral", "Florenta"], correta: 1 },
{ pergunta: "Qual é a classe gramatical da palavra 'rapidamente'?", alternativas: ["Substantivo", "Verbo", "Advérbio", "Adjetivo"], correta: 2 },
{ pergunta: "Qual é o sujeito da frase 'Os alunos estudaram para a prova'?", alternativas: ["Estudaram", "A prova", "Os alunos", "Para a prova"], correta: 2 },
{ pergunta: "Qual destas palavras é um verbo?", alternativas: ["Mesa", "Estudar", "Bonito", "Livro"], correta: 1 },
{ pergunta: "Qual é a principal função da linguagem em uma conversa cotidiana?", alternativas: ["Poética", "Referencial", "Fática", "Metalinguística"], correta: 2 }
],
"Artes": [
{ pergunta: "Qual elemento visual está relacionado às cores e formas em uma obra?", alternativas: ["Composição", "Equação", "Relevo terrestre", "Oxidação"], correta: 0 },
{ pergunta: "A arte rupestre está associada principalmente a qual período?", alternativas: ["Pré-história", "Idade Moderna", "Renascimento", "Século XXI"], correta: 0 },
{ pergunta: "A Mona Lisa foi pintada por:", alternativas: ["Leonardo da Vinci", "Picasso", "Van Gogh", "Michelangelo"], correta: 0 },
{ pergunta: "Qual destes é um tipo de arte visual?", alternativas: ["Pintura", "Futebol", "Natação", "Atletismo"], correta: 0 },
{ pergunta: "O teatro utiliza principalmente:", alternativas: ["Representação de personagens", "Equações", "Mapas", "Experimentos"], correta: 0 },
{ pergunta: "A música é composta por elementos como:", alternativas: ["Ritmo", "Latitude", "pH", "DNA"], correta: 0 },
{ pergunta: "Qual movimento artístico teve Pablo Picasso como destaque?", alternativas: ["Cubismo", "Barroco", "Romantismo", "Realismo"], correta: 0 },
{ pergunta: "O cinema é considerado uma arte porque:", alternativas: ["Expressa ideias e emoções", "Produz energia", "Mede temperatura", "Calcula áreas"], correta: 0 },
{ pergunta: "As cores primárias são:", alternativas: ["Azul, vermelho e amarelo", "Verde, laranja e roxo", "Preto e branco", "Cinza e marrom"], correta: 0 },
{ pergunta: "Van Gogh ficou conhecido principalmente por suas:", alternativas: ["Pinturas", "Esculturas", "Peças teatrais", "Sinfonias"], correta: 0 },
{ pergunta: "A dança é uma forma de expressão:", alternativas: ["Corporal", "Química", "Matemática", "Geográfica"], correta: 0 },
{ pergunta: "A escultura utiliza materiais como:", alternativas: ["Pedra e argila", "Oxigênio", "Papel apenas", "Luz"], correta: 0 },
{ pergunta: "O grafite é uma manifestação artística encontrada:", alternativas: ["Em espaços urbanos", "Somente em museus", "Somente em escolas", "Apenas em teatros"], correta: 0 },
{ pergunta: "A fotografia registra:", alternativas: ["Imagens", "Sons", "Temperaturas", "Cheiros"], correta: 0 },
{ pergunta: "O Renascimento valorizava:", alternativas: ["Arte e conhecimento", "Ignorância", "Guerra", "Isolamento"], correta: 0 },
{ pergunta: "A arte pode contribuir para:", alternativas: ["Expressão cultural", "Poluição", "Extinção", "Desinformação"], correta: 0 },
{ pergunta: "O teatro surgiu na:", alternativas: ["Grécia Antiga", "Brasil", "China Moderna", "Austrália"], correta: 0 },
{ pergunta: "A música clássica utiliza principalmente:", alternativas: ["Instrumentos musicais", "Motores", "Computadores", "Satélites"], correta: 0 },
{ pergunta: "O desenho é uma forma de arte baseada em:", alternativas: ["Linhas e formas", "Equações", "Substâncias químicas", "Movimentos planetários"], correta: 0 },
{ pergunta: "A arte permite:", alternativas: ["Criatividade", "Somente memorização", "Ausência de expressão", "Padronização absoluta"], correta: 0 }
],
"Educação Física": [
{ pergunta: "Qual prática ajuda a reduzir o risco de lesões antes de uma atividade física?", alternativas: ["Aquecimento", "Jejum prolongado", "Sono reduzido", "Sedentarismo"], correta: 0 },
{ pergunta: "Em esportes coletivos, a cooperação está relacionada a:", alternativas: ["Trabalho em equipe", "Isolamento", "Desorganização", "Falta de regras"], correta: 0 },
{ pergunta: "Qual destes é considerado exercício aeróbico?", alternativas: ["Caminhada", "Levantamento de peso máximo", "Xadrez", "Dormir"], correta: 0 },
{ pergunta: "A prática regular de exercícios contribui para:", alternativas: ["Saúde", "Sedentarismo", "Doenças", "Isolamento"], correta: 0 },
{ pergunta: "Qual esporte utiliza uma bola de basquete?", alternativas: ["Basquete", "Vôlei", "Tênis", "Handebol"], correta: 0 },
{ pergunta: "O futebol é praticado principalmente com:", alternativas: ["Os pés", "As mãos", "A cabeça apenas", "Raquetes"], correta: 0 },
{ pergunta: "O alongamento ajuda a melhorar:", alternativas: ["Flexibilidade", "Preguiça", "Sedentarismo", "Desidratação"], correta: 0 },
{ pergunta: "Qual destes é um esporte olímpico?", alternativas: ["Atletismo", "Queimada", "Amarelinha", "Pega-pega"], correta: 0 },
{ pergunta: "A hidratação é importante porque:", alternativas: ["Mantém o organismo funcionando adequadamente", "Substitui refeições", "Evita exercícios", "Aumenta o sono"], correta: 0 },
{ pergunta: "A frequência cardíaca tende a:", alternativas: ["Aumentar durante exercícios", "Parar", "Diminuir sempre", "Não mudar"], correta: 0 },
{ pergunta: "Qual destes é um esporte coletivo?", alternativas: ["Vôlei", "Natação", "Judô", "Atletismo"], correta: 0 },
{ pergunta: "O sedentarismo pode causar:", alternativas: ["Problemas de saúde", "Melhor condicionamento", "Maior resistência", "Mais flexibilidade"], correta: 0 },
{ pergunta: "O vôlei é jogado por equipes separadas por:", alternativas: ["Rede", "Parede", "Piscina", "Pista"], correta: 0 },
{ pergunta: "A corrida melhora principalmente:", alternativas: ["Condicionamento cardiorrespiratório", "Visão", "Audição", "Memória fotográfica"], correta: 0 },
{ pergunta: "A Educação Física também trabalha:", alternativas: ["Respeito e cooperação", "Somente competição", "Somente força", "Somente velocidade"], correta: 0 },
{ pergunta: "Qual destes é um esporte de combate?", alternativas: ["Judô", "Vôlei", "Basquete", "Futebol"], correta: 0 },
{ pergunta: "O descanso é importante porque:", alternativas: ["Auxilia na recuperação do corpo", "Substitui exercícios", "Impede aprendizado", "Reduz a saúde"], correta: 0 },
{ pergunta: "Uma alimentação equilibrada contribui para:", alternativas: ["Melhor desempenho físico", "Pior saúde", "Sedentarismo", "Desidratação"], correta: 0 },
{ pergunta: "O atletismo inclui modalidades como:", alternativas: ["Corridas e saltos", "Xadrez", "Tênis de mesa apenas", "Sinuca"], correta: 0 },
{ pergunta: "A atividade física regular pode ajudar a:", alternativas: ["Melhorar a qualidade de vida", "Reduzir a saúde", "Aumentar o sedentarismo", "Diminuir a resistência"], correta: 0 }
],
"Inglês": [
{ pergunta: "Qual é a tradução de 'school'?", alternativas: ["Escola", "Livro", "Janela", "Rua"], correta: 0 },
{ pergunta: "Complete: I ___ a student.", alternativas: ["am", "is", "are", "be"], correta: 0 },
{ pergunta: "Qual é a tradução de 'book'?", alternativas: ["Mesa", "Livro", "Caneta", "Escola"], correta: 1 },
{ pergunta: "Complete: She ___ my friend.", alternativas: ["am", "are", "is", "be"], correta: 2 },
{ pergunta: "Qual é a tradução de 'teacher'?", alternativas: ["Professor", "Aluno", "Diretor", "Funcionário"], correta: 0 },
{ pergunta: "Qual palavra significa 'cachorro'?", alternativas: ["Cat", "Dog", "Bird", "Fish"], correta: 1 },
{ pergunta: "Complete: They ___ happy.", alternativas: ["is", "am", "are", "be"], correta: 2 },
{ pergunta: "Qual é a tradução de 'house'?", alternativas: ["Escola", "Casa", "Prédio", "Rua"], correta: 1 },
{ pergunta: "Qual é o plural de 'book'?", alternativas: ["Bookes", "Books", "Books'", "Book"], correta: 1 },
{ pergunta: "Qual palavra significa 'água'?", alternativas: ["Milk", "Juice", "Water", "Coffee"], correta: 2 },
{ pergunta: "Qual é a tradução de 'car'?", alternativas: ["Carro", "Casa", "Cidade", "Rua"], correta: 0 },
{ pergunta: "Complete: We ___ friends.", alternativas: ["is", "am", "are", "be"], correta: 2 },
{ pergunta: "Qual é a tradução de 'red'?", alternativas: ["Azul", "Verde", "Amarelo", "Vermelho"], correta: 3 },
{ pergunta: "Qual palavra significa 'gato'?", alternativas: ["Dog", "Cat", "Bird", "Fish"], correta: 1 },
{ pergunta: "Qual é a tradução de 'computer'?", alternativas: ["Telefone", "Computador", "Livro", "Mesa"], correta: 1 },
{ pergunta: "Complete: He ___ at school.", alternativas: ["am", "is", "are", "be"], correta: 1 },
{ pergunta: "Qual é a tradução de 'sun'?", alternativas: ["Lua", "Estrela", "Sol", "Céu"], correta: 2 },
{ pergunta: "Qual é a tradução de 'friend'?", alternativas: ["Colega", "Amigo", "Professor", "Aluno"], correta: 1 },
{ pergunta: "Qual palavra significa 'cidade'?", alternativas: ["Country", "Village", "City", "Street"], correta: 2 },
{ pergunta: "Qual é a tradução de 'good morning'?", alternativas: ["Boa noite", "Boa tarde", "Bom dia", "Até logo"], correta: 2 }
],
"Matemática": [
{ pergunta: "Quanto é 8 × 7?", alternativas: ["54", "56", "64", "58"], correta: 1 },
{ pergunta: "Qual é o valor de 15% de 200?", alternativas: ["15", "20", "30", "40"], correta: 2 },
{ pergunta: "Quanto é 12²?", alternativas: ["124", "122", "144", "142"], correta: 2 },
{ pergunta: "Qual é a raiz quadrada de 81?", alternativas: ["7", "8", "9", "10"], correta: 2 },
{ pergunta: "Quanto é 25% de 80?", alternativas: ["10", "15", "20", "25"], correta: 2 },
{ pergunta: "Quanto é 3/4 de 100?", alternativas: ["25", "50", "75", "80"], correta: 2 },
{ pergunta: "O resultado de 2³ é:", alternativas: ["4", "6", "8", "16"], correta: 2 },
{ pergunta: "Qual é o perímetro de um quadrado de lado 5 cm?", alternativas: ["10", "15", "20", "25"], correta: 2 },
{ pergunta: "Quanto é 0,5 + 0,25?", alternativas: ["0,75", "0,65", "0,80", "0,55"], correta: 0 },
{ pergunta: "Qual é o valor de x em x + 7 = 15?", alternativas: ["6", "7", "8", "9"], correta: 2 },
{ pergunta: "Quanto é 9 × 9?", alternativas: ["72", "81", "99", "90"], correta: 1 },
{ pergunta: "Qual é a área de um retângulo de 5 m por 4 m?", alternativas: ["9", "18", "20", "25"], correta: 2 },
{ pergunta: "Quanto é 100 ÷ 4?", alternativas: ["20", "25", "30", "40"], correta: 1 },
{ pergunta: "Qual é a soma dos ângulos internos de um triângulo?", alternativas: ["90°", "180°", "270°", "360°"], correta: 1 },
{ pergunta: "Qual número é primo?", alternativas: ["9", "15", "17", "21"], correta: 2 },
{ pergunta: "Quanto é 7²?", alternativas: ["14", "49", "42", "56"], correta: 1 },
{ pergunta: "Uma dúzia corresponde a:", alternativas: ["10", "11", "12", "13"], correta: 2 },
{ pergunta: "Quanto é 20% de 150?", alternativas: ["25", "30", "35", "40"], correta: 1 },
{ pergunta: "Qual é o MMC de 4 e 6?", alternativas: ["10", "12", "18", "24"], correta: 1 },
{ pergunta: "Qual é o valor de π aproximadamente?", alternativas: ["2,14", "3,14", "4,13", "3,41"], correta: 1 }
],
"Biologia": [
{ pergunta: "Qual organela é conhecida como responsável pela respiração celular?", alternativas: ["Mitocôndria", "Ribossomo", "Núcleo", "Lisossomo"], correta: 0 },
{ pergunta: "O DNA está relacionado principalmente à:", alternativas: ["Informação genética", "Digestão", "Contração muscular", "Evaporação"], correta: 0 },
{ pergunta: "A unidade básica da vida é:", alternativas: ["Átomo", "Molécula", "Célula", "Tecido"], correta: 2 },
{ pergunta: "Os vegetais produzem alimento por meio da:", alternativas: ["Respiração", "Fotossíntese", "Fermentação", "Digestão"], correta: 1 },
{ pergunta: "O sangue humano é bombeado pelo:", alternativas: ["Pulmão", "Fígado", "Coração", "Rim"], correta: 2 },
{ pergunta: "Qual gás é utilizado na respiração celular?", alternativas: ["Oxigênio", "Nitrogênio", "Hélio", "Hidrogênio"], correta: 0 },
{ pergunta: "Os pulmões fazem parte do sistema:", alternativas: ["Digestório", "Respiratório", "Nervoso", "Locomotor"], correta: 1 },
{ pergunta: "A hereditariedade está relacionada aos:", alternativas: ["Genes", "Pulmões", "Músculos", "Ossos"], correta: 0 },
{ pergunta: "A fotossíntese ocorre principalmente em qual organela?", alternativas: ["Cloroplasto", "Mitocôndria", "Núcleo", "Ribossomo"], correta: 0 },
{ pergunta: "Os seres humanos pertencem ao reino:", alternativas: ["Animal", "Vegetal", "Fungi", "Protista"], correta: 0 },
{ pergunta: "A água é importante porque:", alternativas: ["Participa das reações metabólicas", "Substitui alimentos", "Produz oxigênio sozinha", "Elimina genes"], correta: 0 },
{ pergunta: "O sistema nervoso é responsável por:", alternativas: ["Coordenação do organismo", "Digestão", "Respiração", "Circulação"], correta: 0 },
{ pergunta: "O principal órgão do sistema nervoso é:", alternativas: ["Pulmão", "Fígado", "Cérebro", "Rim"], correta: 2 },
{ pergunta: "As plantas absorvem água principalmente pelas:", alternativas: ["Folhas", "Flores", "Raízes", "Sementes"], correta: 2 },
{ pergunta: "Os ossos fazem parte do sistema:", alternativas: ["Respiratório", "Esquelético", "Digestório", "Circulatório"], correta: 1 },
{ pergunta: "A biodiversidade refere-se à:", alternativas: ["Variedade de seres vivos", "Quantidade de água", "Número de montanhas", "Temperatura média"], correta: 0 },
{ pergunta: "Qual destes é um vertebrado?", alternativas: ["Minhoca", "Aranha", "Peixe", "Polvo"], correta: 2 },
{ pergunta: "A dengue é transmitida por:", alternativas: ["Mosquito", "Água", "Ar", "Alimento"], correta: 0 },
{ pergunta: "Os fungos obtêm alimento principalmente por:", alternativas: ["Fotossíntese", "Absorção", "Respiração", "Locomoção"], correta: 1 },
{ pergunta: "O ecossistema é formado pela interação entre:", alternativas: ["Seres vivos e ambiente", "Somente animais", "Somente plantas", "Somente água"], correta: 0 }
],
"Física": [
{ pergunta: "A unidade de medida de força no Sistema Internacional é:", alternativas: ["Newton", "Joule", "Watt", "Metro"], correta: 0 },
{ pergunta: "Velocidade média pode ser calculada por:", alternativas: ["Distância dividida pelo tempo", "Massa vezes volume", "Força dividida pela área", "Temperatura vezes tempo"], correta: 0 },
{ pergunta: "A unidade de medida da energia é:", alternativas: ["Newton", "Joule", "Pascal", "Ampère"], correta: 1 },
{ pergunta: "Qual é a unidade de potência?", alternativas: ["Watt", "Metro", "Joule", "Newton"], correta: 0 },
{ pergunta: "Um corpo em repouso possui velocidade:", alternativas: ["1 m/s", "10 m/s", "0 m/s", "100 m/s"], correta: 2 },
{ pergunta: "A aceleração da gravidade na Terra é aproximadamente:", alternativas: ["9,8 m/s²", "98 m/s²", "0,98 m/s²", "1 m/s²"], correta: 0 },
{ pergunta: "Qual aparelho mede a corrente elétrica?", alternativas: ["Voltímetro", "Amperímetro", "Termômetro", "Barômetro"], correta: 1 },
{ pergunta: "Qual é a unidade de tensão elétrica?", alternativas: ["Volt", "Ampère", "Ohm", "Watt"], correta: 0 },
{ pergunta: "A resistência elétrica é medida em:", alternativas: ["Volts", "Ampères", "Ohms", "Watts"], correta: 2 },
{ pergunta: "A energia armazenada em alimentos é:", alternativas: ["Química", "Mecânica", "Elétrica", "Sonora"], correta: 0 },
{ pergunta: "O som se propaga por meio de:", alternativas: ["Ondas", "Elétrons", "Luz", "Campo magnético"], correta: 0 },
{ pergunta: "A luz do Sol chega à Terra por:", alternativas: ["Condução", "Convecção", "Radiação", "Compressão"], correta: 2 },
{ pergunta: "Qual é o estado de movimento de um objeto com velocidade constante?", alternativas: ["Acelerado", "Retardado", "Uniforme", "Oscilatório"], correta: 2 },
{ pergunta: "A força que nos mantém presos ao chão é:", alternativas: ["Atrito", "Gravitacional", "Magnética", "Elástica"], correta: 1 },
{ pergunta: "A velocidade da luz é aproximadamente:", alternativas: ["300 mil km/s", "30 mil km/s", "3 mil km/s", "3 milhões km/s"], correta: 0 },
{ pergunta: "O calor sempre flui do corpo:", alternativas: ["Mais frio para o mais quente", "Mais quente para o mais frio", "Maior para o menor", "Menor para o maior"], correta: 1 },
{ pergunta: "Qual é a principal fonte de energia da Terra?", alternativas: ["Lua", "Sol", "Vento", "Água"], correta: 1 },
{ pergunta: "O atrito tende a:", alternativas: ["Aumentar o movimento", "Diminuir o movimento", "Criar energia", "Anular a gravidade"], correta: 1 },
{ pergunta: "A energia cinética está associada:", alternativas: ["Ao movimento", "Ao calor", "À eletricidade", "À massa"], correta: 0 },
{ pergunta: "A energia potencial gravitacional depende da:", alternativas: ["Altura", "Cor", "Temperatura", "Velocidade da luz"], correta: 0 }
],
"Química": [
{ pergunta: "Qual é o símbolo químico do sódio?", alternativas: ["So", "Na", "Sd", "S"], correta: 1 },
{ pergunta: "Uma substância com pH menor que 7 é geralmente considerada:", alternativas: ["Ácida", "Básica", "Neutra", "Metálica"], correta: 0 },
{ pergunta: "Qual é o símbolo químico do oxigênio?", alternativas: ["Ox", "O", "Og", "Oi"], correta: 1 },
{ pergunta: "Qual elemento possui símbolo Fe?", alternativas: ["Fósforo", "Flúor", "Ferro", "Frâncio"], correta: 2 },
{ pergunta: "A água possui fórmula química:", alternativas: ["CO₂", "H₂O", "NaCl", "O₂"], correta: 1 },
{ pergunta: "Qual partícula possui carga negativa?", alternativas: ["Próton", "Nêutron", "Elétron", "Núcleo"], correta: 2 },
{ pergunta: "Qual é o número atômico do carbono?", alternativas: ["6", "8", "12", "14"], correta: 0 },
{ pergunta: "O gás carbônico possui fórmula:", alternativas: ["CO₂", "CO", "O₂", "CH₄"], correta: 0 },
{ pergunta: "Qual destes é um metal?", alternativas: ["Ferro", "Oxigênio", "Cloro", "Nitrogênio"], correta: 0 },
{ pergunta: "A tabela periódica organiza os elementos por:", alternativas: ["Massa corporal", "Número atômico", "Volume", "Temperatura"], correta: 1 },
{ pergunta: "Qual é o símbolo químico do ouro?", alternativas: ["Au", "Ag", "Go", "Or"], correta: 0 },
{ pergunta: "Qual é o símbolo químico da prata?", alternativas: ["Pt", "Pr", "Ag", "Pa"], correta: 2 },
{ pergunta: "O sal de cozinha é composto principalmente por:", alternativas: ["NaCl", "H₂O", "CO₂", "KCl"], correta: 0 },
{ pergunta: "O pH da água pura é aproximadamente:", alternativas: ["1", "5", "7", "14"], correta: 2 },
{ pergunta: "Qual substância é considerada básica?", alternativas: ["Suco de limão", "Vinagre", "Leite de magnésia", "Refrigerante"], correta: 2 },
{ pergunta: "A mudança de estado de sólido para líquido chama-se:", alternativas: ["Fusão", "Evaporação", "Condensação", "Sublimação"], correta: 0 },
{ pergunta: "Qual destes é um gás nobre?", alternativas: ["Hélio", "Oxigênio", "Cloro", "Carbono"], correta: 0 },
{ pergunta: "Qual elemento é essencial para a respiração humana?", alternativas: ["Nitrogênio", "Oxigênio", "Hélio", "Argônio"], correta: 1 },
{ pergunta: "Mistura homogênea apresenta:", alternativas: ["Uma fase", "Duas fases", "Três fases", "Partículas visíveis"], correta: 0 },
{ pergunta: "Qual é o símbolo químico do potássio?", alternativas: ["Po", "Pt", "K", "Ka"], correta: 2 },
{ pergunta: "Qual destas substâncias é composta?", alternativas: ["Oxigênio", "Ferro", "Água", "Ouro"], correta: 2 }
],
"História": [
{ pergunta: "A Proclamação da República no Brasil ocorreu em:", alternativas: ["1822", "1889", "1500", "1930"], correta: 1 },
{ pergunta: "A Revolução Industrial teve início principalmente em qual país?", alternativas: ["Inglaterra", "Brasil", "Egito", "Japão"], correta: 0 },
{ pergunta: "Quem foi o primeiro imperador do Brasil?", alternativas: ["Dom Pedro I", "Dom Pedro II", "Getúlio Vargas", "Tiradentes"], correta: 0 },
{ pergunta: "O descobrimento do Brasil ocorreu em:", alternativas: ["1492", "1500", "1822", "1889"], correta: 1 },
{ pergunta: "A Independência do Brasil ocorreu em:", alternativas: ["1500", "1889", "1822", "1930"], correta: 2 },
{ pergunta: "Quem liderou a Inconfidência Mineira?", alternativas: ["Tiradentes", "Cabral", "Getúlio Vargas", "Dom Pedro II"], correta: 0 },
{ pergunta: "A Primeira Guerra Mundial ocorreu entre:", alternativas: ["1914-1918", "1939-1945", "1808-1822", "1889-1894"], correta: 0 },
{ pergunta: "A Segunda Guerra Mundial ocorreu entre:", alternativas: ["1914-1918", "1939-1945", "1822-1825", "1950-1954"], correta: 1 },
{ pergunta: "O regime militar no Brasil iniciou-se em:", alternativas: ["1964", "1889", "1930", "1988"], correta: 0 },
{ pergunta: "Quem foi o líder da Alemanha Nazista?", alternativas: ["Hitler", "Stalin", "Churchill", "Roosevelt"], correta: 0 },
{ pergunta: "A escravidão foi abolida no Brasil em:", alternativas: ["1500", "1822", "1888", "1889"], correta: 2 },
{ pergunta: "A Lei Áurea foi assinada por:", alternativas: ["Princesa Isabel", "Dom Pedro I", "Getúlio Vargas", "Tiradentes"], correta: 0 },
{ pergunta: "A capital do Brasil foi transferida para Brasília em:", alternativas: ["1960", "1889", "1822", "1500"], correta: 0 },
{ pergunta: "Os egípcios antigos ficaram conhecidos pelas:", alternativas: ["Pirâmides", "Caravelas", "Ferrovias", "Fábricas"], correta: 0 },
{ pergunta: "A democracia ateniense surgiu na:", alternativas: ["Grécia Antiga", "Roma", "Egito", "Mesopotâmia"], correta: 0 },
{ pergunta: "Quem chegou ao Brasil em 1500?", alternativas: ["Pedro Álvares Cabral", "Vasco da Gama", "Cristóvão Colombo", "Napoleão"], correta: 0 },
{ pergunta: "A Revolução Francesa começou em:", alternativas: ["1789", "1822", "1500", "1914"], correta: 0 },
{ pergunta: "A Idade Média ocorreu entre:", alternativas: ["Séculos V e XV", "Séculos XV e XX", "Séculos I e V", "Séculos XVIII e XIX"], correta: 0 },
{ pergunta: "O Muro de Berlim caiu em:", alternativas: ["1989", "1945", "1964", "2000"], correta: 0 },
{ pergunta: "A Constituição brasileira atualmente em vigor foi promulgada em:", alternativas: ["1988", "1964", "1822", "1889"], correta: 0 }
],
"Geografia": [
{ pergunta: "Qual é o maior bioma brasileiro em extensão?", alternativas: ["Amazônia", "Caatinga", "Pampa", "Pantanal"], correta: 0 },
{ pergunta: "O movimento de rotação da Terra está relacionado a:", alternativas: ["Dia e noite", "Estações do ano", "Marés apenas", "Fases da Lua"], correta: 0 },
{ pergunta: "Qual é o maior oceano do planeta?", alternativas: ["Atlântico", "Índico", "Ártico", "Pacífico"], correta: 3 },
{ pergunta: "Qual é a capital do Espírito Santo?", alternativas: ["Serra", "Vila Velha", "Vitória", "Cariacica"], correta: 2 },
{ pergunta: "O movimento de translação da Terra dura aproximadamente:", alternativas: ["24 horas", "30 dias", "365 dias", "12 horas"], correta: 2 },
{ pergunta: "Qual é o maior país da América do Sul?", alternativas: ["Argentina", "Brasil", "Chile", "Peru"], correta: 1 },
{ pergunta: "O clima predominante na Amazônia é:", alternativas: ["Desértico", "Polar", "Equatorial", "Mediterrâneo"], correta: 2 },
{ pergunta: "Qual linha divide a Terra em hemisfério norte e sul?", alternativas: ["Trópico de Capricórnio", "Linha do Equador", "Meridiano de Greenwich", "Trópico de Câncer"], correta: 1 },
{ pergunta: "Qual é o maior continente do mundo?", alternativas: ["África", "Europa", "Ásia", "América"], correta: 2 },
{ pergunta: "O Brasil está localizado em qual continente?", alternativas: ["Europa", "África", "América", "Ásia"], correta: 2 },
{ pergunta: "Qual destes é um recurso natural renovável?", alternativas: ["Petróleo", "Carvão", "Energia solar", "Gás natural"], correta: 2 },
{ pergunta: "O Pantanal é conhecido principalmente por sua:", alternativas: ["Biodiversidade", "Neve", "Industrialização", "Desertificação"], correta: 0 },
{ pergunta: "Qual é a capital do Brasil?", alternativas: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"], correta: 2 },
{ pergunta: "O mapa é uma representação:", alternativas: ["Matemática", "Cartográfica", "Biológica", "Histórica"], correta: 1 },
{ pergunta: "Qual é o principal gás responsável pelo efeito estufa?", alternativas: ["Oxigênio", "Nitrogênio", "CO₂", "Hélio"], correta: 2 },
{ pergunta: "Qual região brasileira possui maior extensão territorial?", alternativas: ["Sul", "Sudeste", "Centro-Oeste", "Norte"], correta: 3 },
{ pergunta: "A população mundial está concentrada principalmente:", alternativas: ["Nas áreas habitáveis", "Nos desertos", "Nos polos", "Nos oceanos"], correta: 0 },
{ pergunta: "Qual destes é um país da América do Sul?", alternativas: ["Canadá", "México", "Uruguai", "Portugal"], correta: 2 },
{ pergunta: "A urbanização corresponde ao crescimento das:", alternativas: ["Florestas", "Áreas urbanas", "Montanhas", "Lavouras"], correta: 1 },
{ pergunta: "O Espírito Santo pertence à região:", alternativas: ["Sul", "Nordeste", "Sudeste", "Centro-Oeste"], correta: 2 }
],
"Sociologia": [
{ pergunta: "A Sociologia estuda principalmente:", alternativas: ["Relações sociais", "Composição química", "Órbitas planetárias", "Células"], correta: 0 },
{ pergunta: "Cultura pode ser entendida como:", alternativas: ["Conjunto de práticas, valores e costumes", "Apenas obras em museus", "Somente música clássica", "Somente tecnologia"], correta: 0 },
{ pergunta: "O conceito de cidadania está relacionado a:", alternativas: ["Direitos e deveres", "Somente votar", "Somente trabalhar", "Somente estudar"], correta: 0 },
{ pergunta: "A família é considerada uma:", alternativas: ["Instituição social", "Empresa", "Partido político", "Indústria"], correta: 0 },
{ pergunta: "Desigualdade social refere-se às diferenças de:", alternativas: ["Acesso a recursos e oportunidades", "Clima", "Relevo", "Vegetação"], correta: 0 },
{ pergunta: "A escola é um exemplo de:", alternativas: ["Instituição social", "Fenômeno químico", "Ecossistema", "Reação física"], correta: 0 },
{ pergunta: "A diversidade cultural representa:", alternativas: ["Variedade de culturas", "Somente arte", "Somente religião", "Somente idioma"], correta: 0 },
{ pergunta: "O trabalho é importante porque:", alternativas: ["Produz bens e serviços", "Impede a educação", "Elimina a cultura", "Substitui a cidadania"], correta: 0 },
{ pergunta: "Preconceito é:", alternativas: ["Julgamento prévio", "Pesquisa científica", "Debate democrático", "Processo educativo"], correta: 0 },
{ pergunta: "A participação política pode ocorrer por meio de:", alternativas: ["Voto", "Somente impostos", "Somente trabalho", "Somente consumo"], correta: 0 },
{ pergunta: "Movimentos sociais buscam:", alternativas: ["Defender interesses coletivos", "Aumentar preços", "Controlar o clima", "Produzir energia"], correta: 0 },
{ pergunta: "O respeito às diferenças contribui para:", alternativas: ["Convivência social", "Conflitos", "Violência", "Exclusão"], correta: 0 },
{ pergunta: "A globalização intensificou:", alternativas: ["Conexões entre países", "O isolamento", "A extinção da tecnologia", "A redução das comunicações"], correta: 0 },
{ pergunta: "Consumismo significa:", alternativas: ["Consumo excessivo", "Economia de recursos", "Produção agrícola", "Educação financeira"], correta: 0 },
{ pergunta: "Os direitos humanos defendem:", alternativas: ["Dignidade e igualdade", "Privilégios de grupos", "Exclusão social", "Violência"], correta: 0 },
{ pergunta: "A democracia envolve:", alternativas: ["Participação popular", "Governo sem leis", "Ausência de direitos", "Fim das eleições"], correta: 0 },
{ pergunta: "O bullying é um problema relacionado à:", alternativas: ["Convivência social", "Astronomia", "Cartografia", "Ecologia"], correta: 0 },
{ pergunta: "A ética está relacionada a:", alternativas: ["Valores e comportamentos", "Reações químicas", "Mapas", "Genética"], correta: 0 },
{ pergunta: "O voluntariado contribui para:", alternativas: ["Solidariedade", "Individualismo", "Exclusão", "Preconceito"], correta: 0 },
{ pergunta: "A inclusão social busca:", alternativas: ["Garantir participação de todos", "Criar desigualdades", "Reduzir direitos", "Impedir o acesso à educação"], correta: 0 }
],
"Filosofia": [
{ pergunta: "A Filosofia busca desenvolver principalmente:", alternativas: ["Reflexão crítica", "Memorização sem debate", "Cálculo de massa molar", "Treino físico"], correta: 0 },
{ pergunta: "A palavra filosofia significa, em origem grega:", alternativas: ["Amor à sabedoria", "Medo da ciência", "Estudo dos mapas", "Arte da guerra"], correta: 0 },
{ pergunta: "Quem é conhecido como mestre de Platão?", alternativas: ["Sócrates", "Aristóteles", "Descartes", "Kant"], correta: 0 },
{ pergunta: "Platão fundou a:", alternativas: ["Academia", "Universidade de Atenas", "Biblioteca", "Escola Moderna"], correta: 0 },
{ pergunta: "Aristóteles foi discípulo de:", alternativas: ["Sócrates", "Platão", "Descartes", "Nietzsche"], correta: 1 },
{ pergunta: "A ética estuda principalmente:", alternativas: ["O comportamento humano", "Os planetas", "As células", "Os números"], correta: 0 },
{ pergunta: "A lógica está relacionada ao:", alternativas: ["Raciocínio correto", "Sistema solar", "Corpo humano", "Relevo"], correta: 0 },
{ pergunta: "Quem afirmou 'Penso, logo existo'?", alternativas: ["Descartes", "Platão", "Aristóteles", "Sócrates"], correta: 0 },
{ pergunta: "A Filosofia surgiu na:", alternativas: ["Grécia Antiga", "Roma", "Egito", "Mesopotâmia"], correta: 0 },
{ pergunta: "A política é estudada pela Filosofia porque envolve:", alternativas: ["Organização da sociedade", "Movimento dos planetas", "Composição química", "Digestão"], correta: 0 },
{ pergunta: "O diálogo era uma característica marcante do método de:", alternativas: ["Sócrates", "Newton", "Darwin", "Galileu"], correta: 0 },
{ pergunta: "A reflexão filosófica busca:", alternativas: ["Questionar e compreender", "Memorizar apenas", "Evitar dúvidas", "Ignorar problemas"], correta: 0 },
{ pergunta: "A liberdade é um tema comum em:", alternativas: ["Filosofia", "Cartografia", "Geologia", "Astronomia"], correta: 0 },
{ pergunta: "A Filosofia ajuda a desenvolver:", alternativas: ["Pensamento crítico", "Força física", "Velocidade", "Reflexos"], correta: 0 },
{ pergunta: "O conhecimento é tema de qual área filosófica?", alternativas: ["Epistemologia", "Cartografia", "Citologia", "Mecânica"], correta: 0 },
{ pergunta: "A ética está ligada à ideia de:", alternativas: ["Valores", "Temperatura", "Distância", "Energia"], correta: 0 },
{ pergunta: "O mito procura explicar a realidade por meio de:", alternativas: ["Narrativas simbólicas", "Experimentos científicos", "Equações", "Mapas"], correta: 0 },
{ pergunta: "A Filosofia incentiva:", alternativas: ["Questionamento", "Obediência sem reflexão", "Preconceito", "Ignorância"], correta: 0 },
{ pergunta: "A democracia foi debatida por filósofos da:", alternativas: ["Grécia Antiga", "Idade Média", "Pré-história", "Revolução Industrial"], correta: 0 },
{ pergunta: "Qual destes é considerado filósofo?", alternativas: ["Platão", "Einstein", "Darwin", "Pasteur"], correta: 0 }
],
};
